name: 'Generate SSH Key Pair'
description: 'Generates an SSH key pair'
author: 'TrueMark'
branding:
  icon: 'check-circle'
  color: 'red'
inputs:
  type:
    required: false
    description: 'Either rsa or ecdsa'
    default: 'ecdsa'
  name:
    required: false
    description: 'The name of the key pair'
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
    private-key-path:
      description: 'The private key path'
    public-key-path:
      description: 'The public key path'
    public-key:
      description: 'The public key'
